---
- hosts: localhost
  connection: local

  tasks:
    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/yoshist/spring2.git'
        dest: spring2

    - name: Go to project directory
      ansible.builtin.shell: cd spring2

    - name: Build and package maven build
      command: mvn -f pom.xml clean package
